apiVersion: v1
kind: Secret
metadata:
  name: aws-access-keys
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVJaREJINDVIV1JETFUzVUY=
  AWS_SECRET_ACCESS_KEY: ZjFvangxcmdaTDhPeEs3cDI0L3RNaWR5RmpGa3dIeFBlNnQ5ZjdXQQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: shaikmustafa/cycle
        name: configsecrets
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-keys
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-access-keys
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
