apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXX
      server: https://api.cloudvishwakarma.in
      tls-server-name: api.internal.cloudvishwakarma.in
    name: cloudvishwakarma.in
contexts:
  - context:
      cluster: cloudvishwakarma.in
      namespace: development
      user: user1
    name: user1-context
current-context: user1-context
kind: Config
users:
  - name: user1
    user:
      client-certificate: /root/user1.crt
      client-key: /root/user1.key


congig files for user1 and user2. make sure to copy only in master node

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0RzQ2w1akhEdy9Qa3ZkeU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TkRJNE1EVTBPRFV4V2hjTk16VXdOREk0TURVMApPRFV4V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdWx0clpTVDBzNTl2dStyenUwdVdqM1pUUzZmRmlqaDFXallMbmY0aHA2N2wKTHkwczlYTmt2MGZaUGVkc05UTVpJcVZHaEw4eTFhNytOZzFiM1hXNW5MdXlJZkpTeHRiL1V3MC84UWpRbGd2ZgpOZUJwRWdXdlZGZ2g0bHZlTytlWUdCZU1FVVIxZjI5bkx5SW0xV0xpZHUybTRydUFPSmttMFNYUXIxcUtScEVECnZGUEVRaEdrMElWT1RGOEpCaDJzanJiNEZNR3J4T25teDJ0cy9YWWhsWnpkM2NUS1BLODB3eE5ON3NIYlUwaWMKQ1EyNHltcktTZEIvVTh2RitQMXFteXFqRVcvemU4VDZicDJWZkhsVmZsTkNWaE02cS9ZQWxSOXRSdDFCR2ZJdQpsRWIxeSsxdGtzZEdQNStCMlZGRU1CdSsxUm9EQ0tLMzdtT1lvRk9hNHdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWNTNGtUSlcvb29ZbWZ6QUMKMDdVODFBaklRYUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlXRjBPVy9pZ2h1cGdoV3hpVXNTYlVVVHFRLwpLWnhlQ1Y1TTNlTDM2NGx1MUJsVWc1RnBGOEtCZTRGcnJEaXNEd3Avek9VV29aTytFZ2JQNHdrK0RwZDduRyswClRXWDc0ekZYMUxMRlJPWTI5bW00QTJNd0N6YWQ2RnRDNEF1dUNZSEhCdWgxMzloRHVXbG15TDdMRUh3MWNRaS8KNml3T0JCVnpJUGcrUmRxM0tDY3B6ai8rZWxtWG0rT0pvUE5VUXA0SlJoWFdJbXpra1k5NXJOaElHTnFycEpnMAo0SWpOVlNvcldsV3JzVXFrU2ZXTUhqcjhnMU1DakhxTlZIVmZTdGNVTVFJMGhYVDVGQkVVdWNOMGNBdUdBeU1oCjU4NVRtS21BZGpwdElxOUY3UVdFZVJPTGdlNUgzQjNnYkdjcFlHUWVISjFWdEpjRllsSVVVT01pSjVrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.gouricloudsols.xyz
    tls-server-name: api.internal.gouricloudsols.xyz
  name: gouricloudsols.xyz
contexts:
- context:
    cluster: gouricloudsols.xyz
    namespace: development
    user: user1
  name: user1-context
current-context: user1-context
kind: Config
preferences: {}
users:
- name: user1
  user:
    client-certificate: /root/user1.crt
    client-key: /root/user1.key
	
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0RzQ2w1akhEdy9Qa3ZkeU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TkRJNE1EVTBPRFV4V2hjTk16VXdOREk0TURVMApPRFV4V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdWx0clpTVDBzNTl2dStyenUwdVdqM1pUUzZmRmlqaDFXallMbmY0aHA2N2wKTHkwczlYTmt2MGZaUGVkc05UTVpJcVZHaEw4eTFhNytOZzFiM1hXNW5MdXlJZkpTeHRiL1V3MC84UWpRbGd2ZgpOZUJwRWdXdlZGZ2g0bHZlTytlWUdCZU1FVVIxZjI5bkx5SW0xV0xpZHUybTRydUFPSmttMFNYUXIxcUtScEVECnZGUEVRaEdrMElWT1RGOEpCaDJzanJiNEZNR3J4T25teDJ0cy9YWWhsWnpkM2NUS1BLODB3eE5ON3NIYlUwaWMKQ1EyNHltcktTZEIvVTh2RitQMXFteXFqRVcvemU4VDZicDJWZkhsVmZsTkNWaE02cS9ZQWxSOXRSdDFCR2ZJdQpsRWIxeSsxdGtzZEdQNStCMlZGRU1CdSsxUm9EQ0tLMzdtT1lvRk9hNHdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWNTNGtUSlcvb29ZbWZ6QUMKMDdVODFBaklRYUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlXRjBPVy9pZ2h1cGdoV3hpVXNTYlVVVHFRLwpLWnhlQ1Y1TTNlTDM2NGx1MUJsVWc1RnBGOEtCZTRGcnJEaXNEd3Avek9VV29aTytFZ2JQNHdrK0RwZDduRyswClRXWDc0ekZYMUxMRlJPWTI5bW00QTJNd0N6YWQ2RnRDNEF1dUNZSEhCdWgxMzloRHVXbG15TDdMRUh3MWNRaS8KNml3T0JCVnpJUGcrUmRxM0tDY3B6ai8rZWxtWG0rT0pvUE5VUXA0SlJoWFdJbXpra1k5NXJOaElHTnFycEpnMAo0SWpOVlNvcldsV3JzVXFrU2ZXTUhqcjhnMU1DakhxTlZIVmZTdGNVTVFJMGhYVDVGQkVVdWNOMGNBdUdBeU1oCjU4NVRtS21BZGpwdElxOUY3UVdFZVJPTGdlNUgzQjNnYkdjcFlHUWVISjFWdEpjRllsSVVVT01pSjVrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.gouricloudsols.xyz
    tls-server-name: api.internal.gouricloudsols.xyz
  name: gouricloudsols.xyz
contexts:
- context:
    cluster: gouricloudsols.xyz
    namespace: production
    user: user2
  name: user2-context
current-context: user2-context
kind: Config
preferences: {}
users:
- name: user2
  user:
    client-certificate: /root/user2.crt
    client-key: /root/user2.key







